### ISSUE TITLE
add support for HPE ILO 4

### ISSUE THREAD

**Issue by balexx** [rebootoio/vaxiin-server#4]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
Add support for ILO 4 based models.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by gairadzi** [comment]
This is handled on the handler, opened an [issue](https://github.com/rebootoio/vaxiin-handler/issues/3) there instead
